# Generated by Django 2.1.5 on 2019-06-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
